version = "1.0"

[main]
name = "Simple Torrent configuration"
services = ["__APP__"]

    [main.config]
    name = "Configuration Options"

        [main.config.download_directory]
        ask = "Set download directory"
        type = "string"
        default = "/home/yunohost.app/__APP__/downloads"
        help = "The directory where downloaded file saves."
        bind = "DownloadDirectory:__FINALPATH__/config.yml"

        [main.config.watch_directory]
        ask = "Set watch directory"
        type = "string"
        default = "/home/yunohost.app/__APP__/torrents"
        help = "The directory where downloaded file saves."
        bind = "WatchDirectory:__FINALPATH__/config.yml"
