packaging_format = 2

id = "cloud-torrent"
name = "Cloud Torrent"
description.en = "Self-hosted remote torrent client"
description.fr = "Client torrent distant auto-hébergé"

version = "0.9.1~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0-only"
admindoc = "https://github.com/jpillora/cloud-torrent/wiki/"
code = "https://github.com/jpillora/cloud-torrent"

[integration]
yunohost = ">= 11.2"
architectures = ["amd64","armhf", "arm64"]
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/cloud-torrent"

    [install.init_main_permission]
    help.en = "If enabled, Simple Torrent will be accessible by people who do not have an account. This can be changed later via the webadmin."
    help.fr = "Si cette case est cochée, Simple Torrent sera accessible aux personnes n’ayant pas de compte. Vous pourrez changer ceci plus tard via la webadmin."
    type = "group"
    default = "visitors"

[resources]

 [resources.sources]
    [resources.sources.main]
    amd64.url = "https://github.com/jpillora/cloud-torrent/releases/download/v0.9.1/cloud-torrent_0.9.1_linux_amd64.gz"
    amd64.sha256 = "21b7ce6eb9be944f7497811aea368a098c1976d61c5ed854a0003e455be13ca1"
    arm64.url = "https://github.com/jpillora/cloud-torrent/releases/download/v0.9.1/cloud-torrent_0.9.1_linux_arm64.gz"
    arm64.sha256 = "a4877e546d1d8844a745c6fbb0490aa43f06815833e23af4d9f37e1ecc198637"
    i386.url = "https://github.com/jpillora/cloud-torrent/releases/download/v0.9.1/cloud-torrent_0.9.1_linux_armv7.gz"
    i386.sha256 = "1038f55c5c6a4b0414e291c647f1b7f4c859f8c0de61a323abd7e087b9095bdc"
    extract   = false
    in_subdir = false

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["torrents", "downloads"]

    [resources.ports]
    main.default = 3000
    peer.default = 50007
    peer.exposed = "Both"

    [resources.permissions]
    main.url = "/"
